apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lumen.fullname" . }}-config
  labels:
    {{- include "lumen.labels" . | nindent 4 }}
data:
  streaming_config_v1_5.yaml: |
    kafka:
      brokers: {{ .Values.ingestor.kafka.brokers | quote }}
      topic: {{ .Values.ingestor.kafka.topic | quote }}
      group: {{ .Values.ingestor.kafka.group | quote }}
    loki:
      url: {{ .Values.ingestor.loki.url | quote }}
      query: {{ .Values.ingestor.loki.query | quote }}
      limit: {{ .Values.ingestor.loki.limit }}
      sinceNs: {{ .Values.ingestor.loki.sinceNs }}
