apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumen.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lumen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.maturity.port }}
      targetPort: maturity
      protocol: TCP
      name: maturity
  selector:
    app.kubernetes.io/name: {{ include "lumen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
